/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman.UI;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author armanmasangkay
 */
public class DrawPane extends javax.swing.JPanel {

    
    private boolean[] drawings;
    /**
     * Creates new form DrawPane
     */
    public DrawPane() {
        initComponents();
        drawings=new boolean[10];
        
    }
    
    @Override
    public void paintComponent( Graphics g ) {
        super.paintComponent(g);
        
        if (drawings[0]){
            g.setColor(Color.red);
            g.fillRect(this.getWidth()-120,this.getHeight()-20,100,10); 
        }
        
        if (drawings[1]){
            g.setColor(Color.green);
            g.fillRect(this.getWidth()-80,this.getHeight()-270,10,250); 
        }
        if (drawings[2]){
             g.setColor(Color.blue);
            g.fillRect(140,32,this.getWidth()-210,10); 
        }
        if (drawings[3]){
             g.setColor(Color.red);
            g.fillRect(160,40,10,20); 
        }
        if (drawings[4]){
            g.setColor(Color.red);
            g.drawOval(140,40,40,40); 
        }
            
       
       
    }
    
    
    //baseline of the post
    public void draw1(){
        drawings[0]=true;
        this.repaint();
    }
    //rod
    public void draw2(){
        drawings[1]=true;
        this.repaint();
    }
    //the horizontal rod
    public void draw3(){
        drawings[2]=true;
        this.repaint();
    }
    
    //rope
    public void draw4(){
        drawings[3]=true;
        this.repaint();
    }
    //head
    public void draw5(){
        drawings[4]=true;
        this.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
